import 'package:ecom_t/src/cart/models/cart_product_model.dart';

List<CartProductModel> cartProductsList = [
  CartProductModel(
    id: '1',
    name: 'Classic T-Shirt',
    price: 19.99,
    originalPrice: 29.99,
    color: 'Blue',
    size: 'M',
    stock: 20,
    rating: 4.5,
    reviews: 120,
    image: 'https://via.placeholder.com/150',
    badge: 'New Arrival',
    description: 'A stylish and comfortable T-shirt made from 100% cotton. Perfect for casual outings or layering.',
  ),
  CartProductModel(
    id: '2',
    name: 'Running Shoes',
    price: 49.99,
    originalPrice: 59.99,
    color: 'Red',
    size: '10',
    stock: 15,
    rating: 4.8,
    reviews: 250,
    image: 'https://via.placeholder.com/150',
    badge: 'Bestseller',
    description: 'Lightweight and durable running shoes designed for maximum comfort and performance on any terrain.',
  ),
  CartProductModel(
    id: '3',
    name: 'Leather Jacket',
    price: 89.99,
    originalPrice: 120.00,
    color: 'Black',
    size: 'L',
    stock: 5,
    rating: 4.7,
    reviews: 90,
    image: 'https://via.placeholder.com/150',
    badge: 'Limited Stock',
    description: 'A premium leather jacket with a modern fit. Perfect for adding edge to any outfit.',
  ),
];
